### ISSUE TITLE
All if's necessary?

### ISSUE THREAD

**Issue by mayisa87** [asharif123/reverse_string#1]
https://github.com/asharif123/reverse_string/blob/5349dc5703ac198d5f88dcc381cfa8339c5f6705/reverse_string/Program.cs#L31-L39

Did you watch the video about else/if? (https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560206)
There are for sure situations where an else and else/if will be necessary. But like here, you could get rid of all the else/ifs

`if (sentenceLength == 0)`
I like that you covered this special case! What you could do is, that you immediately stop and leave the program, after outputing the error message to user. You can exit the Main method if you use the command "return;"

` else if (sentenceLength == 1) `
Why do you need to handle this separately? The message shown to user is the same as for an string with length >1 and the loop will work for a string with 1 character the same as for more characters. So this whole else/if block and the code inside can be deleted

And the last else remaining, surrounding the code for all strings with length>1 can be deleted too. Only the else not the code within the block ;)

**Comment by asharif123** [comment]
fixed issue #1 by getting rid of else statements
